In [1]:
PATH_PREFIX = '../../'
import sys
sys.path.append(PATH_PREFIX)

In [2]:
import torch
import os
import pandas as pd
from utils.predictor.predictor import *
from utils.predictor.predictor_data import *

In [3]:
folder_list = [
    os.path.join(PATH_PREFIX, 'results/lenet_relu_compress_50'),
]

file_list = [
    {'name': 'lenet_GA_save.csv', 'repres': 'chromosome'},
    {'name': 'lenet_PSO_save.csv', 'repres': 'representation'},
    {'name': 'lenet_BH_save.csv', 'repres': 'representation'},
    {'name': 'lenet_RND_save.csv', 'repres': 'representation'},
]


In [4]:
dataset = PredictorDataset(32, folder_list, file_list)

predictor = NetPerfPredict([5, 16, 32, 64, 32, 16])

In [5]:
criterion = torch.nn.L1Loss()
optimizer = torch.optim.Adam(predictor.parameters(), lr=0.0001)

train_net(predictor, criterion, optimizer, dataset, 30, 'cpu')

Epoch: 1/30 --- Time: 3.49s	Train loss: 0.0051	Valid loss: 0.0039	Train accuracy: 1.1738806338604307e-05	Valid accuracy: 2.594154979951194e-05
Epoch: 2/30 --- Time: 3.40s	Train loss: 0.0038	Valid loss: 0.0037	Train accuracy: 1.1716266628492191e-05	Valid accuracy: 2.5722761268846472e-05
Epoch: 3/30 --- Time: 3.20s	Train loss: 0.0037	Valid loss: 0.0036	Train accuracy: 1.1594888558251276e-05	Valid accuracy: 2.5685851325606062e-05
Epoch: 4/30 --- Time: 3.49s	Train loss: 0.0037	Valid loss: 0.0036	Train accuracy: 1.1768423990360507e-05	Valid accuracy: 2.590591935993261e-05
Epoch: 5/30 --- Time: 3.32s	Train loss: 0.0036	Valid loss: 0.0035	Train accuracy: 1.1570840704648605e-05	Valid accuracy: 2.5091893414755985e-05
Epoch: 6/30 --- Time: 3.45s	Train loss: 0.0035	Valid loss: 0.0034	Train accuracy: 1.1467857148380679e-05	Valid accuracy: 2.4840996377269017e-05
Epoch: 7/30 --- Time: 3.18s	Train loss: 0.0034	Valid loss: 0.0034	Train accuracy: 1.1711841128715973e-05	Valid accuracy: 2.537194203050061

In [6]:
for i in range(5, 10):
    print(predictor(dataset.test_dataset[i][0]))

tensor([0.0061], grad_fn=<TanhBackward0>)
tensor([0.0005], grad_fn=<TanhBackward0>)
tensor([0.0022], grad_fn=<TanhBackward0>)
tensor([0.0012], grad_fn=<TanhBackward0>)
tensor([0.0010], grad_fn=<TanhBackward0>)


In [7]:
for i in range(5, 10):
    print(dataset.test_dataset[i])

(tensor([ 6., 13., 47., 13., 41.]), tensor([0.0014]))
(tensor([19., 13., 17., 26.,  5.]), tensor([0.]))
(tensor([21.,  5., 48., 11., 46.]), tensor([0.0098]))
(tensor([16., 11.,  7., 22.,  6.]), tensor([0.0020]))
(tensor([17., 40., 35., 16., 41.]), tensor([-0.0004]))
