## Test with float precisions
inspired by [this link](https://stackoverflow.com/questions/56962100/define-a-custom-float8-in-python-numpy-and-convert-from-to-float16)

the float8 have:
- 1b sign
- 5b exponent
- 2b mantisa

In [1]:
import numpy as np

The starting precision of the network is float32

In [2]:
float32 = np.array([[6.3], [5.557], [0.125], [0.127]], dtype='f4')
float32

array([[6.3  ],
       [5.557],
       [0.125],
       [0.127]], dtype=float32)

Lowering the precision to float16

In [3]:
float16 = np.float16(float32.reshape(-1))
float16

array([6.3  , 5.56 , 0.125, 0.127], dtype=float16)

Lowering the precision to float8

In [4]:
float8s = float16.tobytes()[1::2]
float8s

b'F\x000'

Precision of float8 in float16

In [6]:
float16p = np.frombuffer(np.array(np.frombuffer(float8s, dtype='u1'), dtype='>u2').tobytes(), dtype='f2')
float16p.reshape(float32.shape)

array([6.   , 0.   , 0.125], dtype=float16)

Precision of float8 in float32 (through float16)

In [ ]:
float16s = [str(x) for x in float16p]
float32p = [float(x) for x in float16s]
np.array(float32p, dtype='f4').reshape(float32.shape)

In [ ]:
float16s = [str(x) for x in float16]
float32p = [float(x) for x in float16s]
np.array(float32p, dtype='f4').reshape(float32.shape)

Defining and testing function reflecting upper code

In [ ]:
def reduce_precision(float32:list, type:str='f4') -> list:
    
    if type == 'f4':
        return float32

    float16 = np.float16(float32.reshape(-1))

    if type == 'f2':
        float16s = [str(x) for x in float16]
        return np.array([float(x) for x in float16s], dtype='f4').reshape(float32.shape)

    if type != 'f1':
        raise Exception('reduce_precision err - unknown option')

    float16 

    float8s = float16.tobytes()[1::2]
    list16p = np.frombuffer(np.array(np.frombuffer(float8s, dtype='u1'), dtype='>u2').tobytes(), dtype='f2')
    float16s = [str(x) for x in list16p]
    return np.array([float(x) for x in float16s], dtype='f4').reshape(float32.shape)
    

In [ ]:
array_to_reduce = [[2.3], [2.45555555], [2.5], [2.25], [1.75], [-1.25], [0.125], [0.0625], [0.03125], [0.015625],]

In [ ]:
reduce_precision(np.array(array_to_reduce, dtype='float32'), 'f4')

In [ ]:
reduce_precision(np.array(array_to_reduce, dtype='float32'), 'f2')

In [ ]:
reduce_precision(np.array(array_to_reduce, dtype='float32'), 'f1')